import React from "react";
import {
  Sparkles,
  Eye,
  PaintRoller,
  Shield,
  Droplet,
  SprayCan,
  Palette,
  ShoppingCart,
  Minus,
  Plus,
  Trash2,
  MessageCircle,
  Phone,
  Mail,
  MapPin,
  Clock,
  Star,
  StarHalf,
  ChevronDown,
  CheckCircle2,
  Send,
  X,
  ArrowLeft,
  ArrowRight,
  ShieldCheck,
  Droplets,
  Brush,
  Layers,
  Calculator,
  Home,
  MessageSquare,
  ArrowRightLeft,
  Check,
  Receipt,
  Grid,
  Wind,
  Sun,
  HeartPulse,
  Search,
  Pipette,
  Mountain,
  Leaf,
  Flame,
  MountainSnow,
  PaintBucket,
  Compass,
  Menu,
  ChevronRight,
  ChevronLeft,
  ZoomIn,
  ZoomOut,
  Maximize2,
  RotateCcw,
  HelpCircle,
} from "lucide-react";

const iconMap: Record<string, React.ComponentType<React.SVGProps<SVGSVGElement>>> = {
  auto_awesome: Sparkles,
  visibility: Eye,
  format_paint: PaintRoller,
  shield: Shield,
  water_drop: Droplet,
  cleaning_services: SprayCan,
  palette: Palette,
  shopping_cart: ShoppingCart,
  remove: Minus,
  add: Plus,
  delete: Trash2,
  chat: MessageCircle,
  call: Phone,
  mail: Mail,
  location_on: MapPin,
  schedule: Clock,
  star: Star,
  star_half: StarHalf,
  expand_more: ChevronDown,
  check_circle: CheckCircle2,
  send: Send,
  close: X,
  arrow_back: ArrowLeft,
  arrow_forward: ArrowRight,
  health_and_safety: ShieldCheck,
  opacity: Droplets,
  brush: Brush,
  layers: Layers,
  invert_colors: Droplet,
  calculate: Calculator,
  home_pin: Home,
  forum: MessageSquare,
  swap_horiz: ArrowRightLeft,
  check: Check,
  receipt_long: Receipt,
  grid_view: Grid,
  east: ArrowRight,
  air: Wind,
  wb_sunny: Sun,
  psychiatry: HeartPulse,
  search: Search,
  colorize: Pipette,
  landscape: Mountain,
  eco: Leaf,
  self_improvement: Sparkles,
  local_fire_department: Flame,
  terrain: MountainSnow,
  texture: PaintBucket,

  explore: Compass,
  menu: Menu,
  chevron_right: ChevronRight,
  chevron_left: ChevronLeft,
  chevron_down: ChevronDown,
  zoom_in: ZoomIn,
  zoom_out: ZoomOut,
  maximize: Maximize2,
  refresh: RotateCcw,
};

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: string;
  className?: string;
}

export default function Icon({ name, className = "", ...props }: IconProps) {
  const LucideIcon = iconMap[name] || HelpCircle;
  return (
    <LucideIcon className={className} width="1em" height="1em" {...props} />
  );
}
